spring:
  cloud:
    discovery:
      enabled: true

    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**
            - id: category-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/categories/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
            - id: order-line-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/order-line/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications/**


server:
  port: 8222
