services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: stan
      POSTGRES_PASSWORD: stan
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - micrroservices-net
    restart: unless-stopped


  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'false'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5151:80
    networks:
      - micrroservices-net
    restart: unless-stopped


  mongodb:
    container_name: ms_mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=stan
      - MONGO_INITDB_ROOT_PASSWORD=stan
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    restart: unless-stopped

#  mongo-express:
#    container_name: ms_mongo_express
#    image: mongo-express
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=stan
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=stan
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#    ports:
#      - 8081:8081
#    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  micrroservices-net:
    driver: bridge


volumes:
  postgres:
  pgadmin:
  mongo:
